baseurl                 = "http://www.porimolchandro.com/"
languageCode            = "en-us"
title                   = "Porimol Chandro"
theme                   = "hugo-phlat-theme"

[permalinks]
    post                = "/:year/:month/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"

# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"

[[menu.header]]
    name                = "Resume"
    weight              = 2
    url                 = "/resume/"

[[menu.header]]
    name                = "Projects"
    weight              = 3
    url                 = "/projects/"

[[menu.header]]
    name                = "Source Code"
    weight              = 4
    url                 = "https://github.com/porimol/"

[[menu.header]]
    name                = "About Me"
    weight              = 5
    url                 = "/about/"

[[menu.header]]
    name                = "Contact"
    weight              = 6
    url                 = "/contact/"


# The footer menu will appear as an inline-list at the bottom left of the footer found at the bottom of the screen
[[menu.footer]]
    name                = "Privacy Policy"
    weight              = 1
    url                 = "/privacy-policy/"

[params]
    keywords            = ["porimolchandro", "porimol"]
    description         = "A description that will appear as a default if front matter does not exist"
    google_analytics    = "UA-XXXXX-YY"
    google_adsense      = "ca-pub-XXXXXX"
    disqus              = "shortname"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = ""

# Social media icons and links that appear in the footer
[social]
    twitter             = "https://www.twitter.com/porimolchandro"
    googleplus          = ""
    linkedin            = "https://www.linkedin.com/in/porimolchandro"
    youtube             = ""
    paypal              = ""
    instagram           = ""
    reddit              = ""
    email               = ""
    pinterest           = ""
    wordpress           = ""
